create_clock -period 83.330 -name clock -waveform {0.000 41.660} [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rx]
set_property IOSTANDARD LVCMOS33 [get_ports sclk]
set_property IOSTANDARD LVCMOS33 [get_ports mosi]
set_property IOSTANDARD LVCMOS33 [get_ports miso]
set_property IOSTANDARD LVCMOS33 [get_ports cs]
set_property IOSTANDARD LVCMOS33 [get_ports led_0]
set_property IOSTANDARD LVCMOS33 [get_ports led_1]
set_property IOSTANDARD LVCMOS33 [get_ports push_button_0]
set_property IOSTANDARD LVCMOS33 [get_ports push_button_1]
set_property PACKAGE_PIN L17 [get_ports clock]
set_property PACKAGE_PIN J18 [get_ports uart_tx]
set_property PACKAGE_PIN J17 [get_ports uart_rx]
set_property PACKAGE_PIN E19 [get_ports sclk]
set_property PACKAGE_PIN D18 [get_ports mosi]
set_property PACKAGE_PIN K19 [get_ports cs]
set_property PACKAGE_PIN D19 [get_ports miso]
set_property PACKAGE_PIN A17 [get_ports led_0]
set_property PACKAGE_PIN C16 [get_ports led_1]
set_property PACKAGE_PIN A18 [get_ports push_button_0]
set_property PACKAGE_PIN B18 [get_ports push_button_1]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
