site_name: RVX Documentation
site_author: Rafael Calcada
site_description: RVX is a microcontroller IP core developed in Verilog that implements the RV32I instruction set of RISC-V.
repo_url: https://github.com/rafaelcalcada/rvx
edit_uri: edit/main/docs/
markdown_extensions:
    - abbr
    - attr_list
    - md_in_html
    - tables
    - footnotes
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
        options:
          custom_icons:
            - overrides/.icons
theme:
    name: material
    logo: images/rvx_logo.png
    favicon: images/rvx_favicon.png
    highlightjs: true
    palette:
      primary: white
    features:
        - navigation.tabs
        - navigation.expand
        - navigation.instant
        - navigation.instant.progress
        - content.code.copy
        - content.code.select
extra:
    analytics:
        provider: google
        property: G-6380GKCWC3
extra_css: [extra.css]
plugins:
    - search
docs_dir: docs/
remote_branch: docs
copyright: Copyright (c) RVX contributors
nav:
    - Homepage: 'index.md'    
    - User Guide: 'userguide.md'
    - Hardware Docs: 'hardware.md'
    - Examples:
        - Hello World: 'examples/helloworld.md'
        - FreeRTOS: 'examples/freertos.md'