// SPDX-License-Identifier: MIT
// Copyright (c) 2020-2026 RVX Project Contributors

// Standard library includes
#include <csignal>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>

// Verilator includes
#include "RvxSimulator.h"
#include "RvxSimulator___024root.h"
#include <verilated_fst_c.h>

// Project includes
#include "rvx_simulator_argparser.h"
#include "rvx_simulator_logger.h"

// Global flag to indicate if shutdown has been requested
static bool shutdown_requested = false;

/// @brief Signal handler for interrupts requesting simulator shutdown
/// @param signum Signal number
void request_shutdown(int signum)
{
  if (signum == SIGTERM || signum == SIGINT || signum == SIGQUIT || signum == SIGTSTP)
    shutdown_requested = true;
}

/// @brief Entry point of the RVX Simulator program.
/// @param argc Number of command-line arguments.
/// @param argv Array of command-line argument strings.
/// @return EXIT_SUCCESS on successful completion, or EXIT_FAILURE on error.
int main(int argc, char *argv[])
{

  // Close the simulation if any of the interrupt signals below is received
  // ---------------------------------------------------------------------------

  std::signal(SIGINT, request_shutdown);
  std::signal(SIGTERM, request_shutdown);
  std::signal(SIGQUIT, request_shutdown);
  std::signal(SIGTSTP, request_shutdown);

  // Parse command-line arguments
  // ---------------------------------------------------------------------------

  RvxSimulatorArgs sim_options(argc, argv);

  // Validate program file path
  // ---------------------------------------------------------------------------

  if (!std::filesystem::exists(sim_options.program_path))
  {
    std::cerr << argv[0] << ": program '" << sim_options.program_path << "' not found.\n";
    std::exit(EXIT_FAILURE);
  }
  std::fstream program_file(sim_options.program_path, std::ios::in);
  if (!program_file.is_open())
  {
    std::cerr << argv[0] << ": unable to open '" << sim_options.program_path << "'.\n";
    std::exit(EXIT_FAILURE);
  }

  // Initialize logger and log startup information
  // ---------------------------------------------------------------------------

  RvxSimulatorLogger::Severity verbosity_level =
      sim_options.verbose ? RvxSimulatorLogger::Severity::VERBOSE : RvxSimulatorLogger::Severity::INFO;
  RvxSimulatorLogger logger(std::cout, verbosity_level, sim_options.quiet);
  logger.info("Starting RVX Simulator for program: {}", sim_options.program_path);
  logger.verbose(sim_options.trace_path.empty()
                     ? "Tracing is not enabled."
                     : std::format("Tracing enabled. Output file: {}", sim_options.trace_path));
  logger.verbose(sim_options.dump_path.empty()
                     ? "Memory dump is not enabled."
                     : std::format("Memory dump enabled. Output file: {}", sim_options.dump_path));
  logger.verbose(sim_options.max_cycles == 0
                     ? "Simulating until program signals completion."
                     : std::format("Simulating for a maximum of {} clock cycles", sim_options.max_cycles));

  // Allocate simulation objects
  // ---------------------------------------------------------------------------

  VerilatedContext *contextp = new VerilatedContext;
  RvxSimulator *simulator = new RvxSimulator(contextp);
  VerilatedFstC *tracer = new VerilatedFstC;

  // Handful references for long (and confuse!) names generated by Verilator
  // ---------------------------------------------------------------------------

  auto &tcm = simulator->rootp->rvx_simulator__DOT__rvx_instance__DOT__rvx_tightly_coupled_memory_instance__DOT__tcm;
  auto &rw_address = simulator->rootp->rvx_simulator__DOT__rvx_instance__DOT__controller_rw_address;
  auto &write_request = simulator->rootp->rvx_simulator__DOT__rvx_instance__DOT__controller_write_request;
  auto &write_data = simulator->rootp->rvx_simulator__DOT__rvx_instance__DOT__controller_write_data;
  auto &memory_size = simulator->rootp->rvx_simulator__DOT__MEMORY_SIZE;
  auto &uart_tx_bit_counter =
      simulator->rootp->rvx_simulator__DOT__rvx_instance__DOT__rvx_uart_instance__DOT__tx_bit_counter;

  // Handful lambdas
  // ---------------------------------------------------------------------------

  /// @brief Reads a 32-bit word from the simulated memory.
  /// @param memory_address The byte address to read from.
  auto read_memory = [&tcm](uint32_t memory_address) { return tcm[memory_address >> 2]; };

  /// @brief Returns true if the running program has finished execution.
  /// @note A program signals its end by writing 1 to address 0x00000000.
  auto program_end = [&]() { return (rw_address == 0x00000000 && write_request == 1 && write_data == 0x00000001); };

  // Start the tracer (if enabled)
  // ---------------------------------------------------------------------------

  if (!sim_options.trace_path.empty())
  {
    Verilated::traceEverOn(true);
    simulator->trace(tracer, 99);
    tracer->set_time_resolution("1ns");
    tracer->set_time_unit("1ns");
    tracer->open(sim_options.trace_path.c_str());
  }

  // Reset sequence (for 5 clock cycles)
  // ---------------------------------------------------------------------------

  // Assert reset
  simulator->reset_n = 0;
  simulator->clock = 1;

  // Keep it high for 5 clock cycles
  for (int i = 0; i < 10; i++)
  {
    simulator->clock ^= 1;
    simulator->eval();
    tracer->dump(contextp->time());
    contextp->timeInc(10);
  }

  // Deassert reset
  simulator->reset_n = 1;

  // Memory initialization
  // ---------------------------------------------------------------------------

  std::string line;
  size_t load_address = 0;
  for (unsigned i = 0; i < (memory_size >> 2); i++)
    tcm[i] = 0xdeadbeef; // Initialize memory to known pattern first
  while (std::getline(program_file, line))
  {
    std::istringstream iss(line);
    std::string token_str;
    while (iss >> token_str)
    {
      if (!token_str.empty() && token_str[0] == '@')
      {
        load_address = std::stoul(token_str.substr(1), nullptr, 16);
      }
      else
      {
        if (load_address >= (memory_size >> 2))
        {
          logger.error("Program file '{}' tries to load data beyond memory size at address 0x{:08x}.",
                       sim_options.program_path, load_address << 2);
          std::exit(EXIT_FAILURE);
        }
        tcm[load_address++] = std::stoul(token_str, nullptr, 16);
      }
    }
  }

  // Main simulation loop
  // ---------------------------------------------------------------------------

  int cycle_count = 0;
  bool successful_completion = false;
  while (true)
  {

    // Close simulation if interrupted by signal
    if (shutdown_requested)
    {
      logger.info("Interrupt signal received, shutting down simulation...");
      successful_completion = true;
      break;
    }

    // Toggle clock, update cycle counter and evaluate model
    simulator->clock ^= 1;
    simulator->eval();
    tracer->dump(contextp->time());
    contextp->timeInc(10);

    if (simulator->clock == 0) // Increment cycle count on falling edge
      cycle_count++;

    // Output UART TX characters to console
    if (simulator->clock && rw_address == 0x80000000 && write_request && uart_tx_bit_counter == 0)
    {
      std::cout << (char)write_data;
    }

    // Check for maximum cycle count reached
    if (sim_options.max_cycles && cycle_count >= sim_options.max_cycles)
    {
      logger.info("Maximum cycle count {} reached, finishing simulation...", sim_options.max_cycles);
      successful_completion = true;
      break;
    }

    // Finish if program signals completion
    if (program_end())
    {
      logger.info("Program signaled completion after {} cycles.", cycle_count);

      // Output test signature if requested
      uint32_t start_address = read_memory(0x001FFFF8) >> 2;
      uint32_t stop_address = read_memory(0x001FFFFC) >> 2;
      if (!sim_options.signature_path.empty() && start_address < stop_address)
      {
        std::ofstream signature_file(sim_options.signature_path, std::ios::out | std::ios::trunc);
        if (!signature_file.is_open())
        {
          logger.error("Failed to create memory dump file: {}", sim_options.signature_path);
          successful_completion = false;
          break;
        }
        logger.info("Dumping test signature from 0x{:08x} to 0x{:08x} ({} bytes) to {}", start_address, stop_address,
                    stop_address - start_address, sim_options.signature_path);
        while (start_address < stop_address && start_address < (memory_size >> 2))
        {
          signature_file << std::format("{:08x}\n", tcm[start_address++]);
        }
      }

      // Output memory dump if requested
      if (!sim_options.dump_path.empty())
      {
        std::ofstream dump_file(sim_options.dump_path, std::ios::out | std::ios::trunc);
        if (!dump_file.is_open())
        {
          logger.error("Failed to create memory dump file: {}", sim_options.dump_path);
          successful_completion = false;
          break;
        }
        logger.info("Dumping memory to {}", sim_options.dump_path);
        for (uint32_t addr = 0; addr < (memory_size >> 2); addr++)
        {
          dump_file << std::format("{:08x}\n", tcm[addr]);
        }
      }

      successful_completion = true;
      break;
    }
  }

  // Cleanup and exit
  // ---------------------------------------------------------------------------

  if (tracer->isOpen())
  {
    tracer->flush();
    tracer->close();
  }
  logger.info("Simulation finished.");
  return successful_completion ? EXIT_SUCCESS : EXIT_FAILURE;
}
