create_clock -period 8.000 -name clock -waveform {0.000 4.000} [get_ports clock]
create_clock -period 18.181 -name rvx_clock -waveform {0.000 9.090} [get_nets rvx_clock]
set_property IOSTANDARD LVCMOS33 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports sclk]
set_property IOSTANDARD LVCMOS33 [get_ports mosi]
set_property IOSTANDARD LVCMOS33 [get_ports miso]
set_property IOSTANDARD LVCMOS33 [get_ports cs]
set_property IOSTANDARD LVCMOS33 [get_ports sda]
set_property IOSTANDARD LVCMOS33 [get_ports scl]
set_property IOSTANDARD LVCMOS33 [get_ports led_4]
set_property IOSTANDARD LVCMOS33 [get_ports led_5]
set_property IOSTANDARD LVCMOS33 [get_ports push_button_0]
set_property IOSTANDARD LVCMOS33 [get_ports push_button_1]
set_property PACKAGE_PIN H16 [get_ports clock]
set_property PACKAGE_PIN H15 [get_ports sclk]
set_property PACKAGE_PIN T12 [get_ports mosi]
set_property PACKAGE_PIN F16 [get_ports cs]
set_property PACKAGE_PIN W15 [get_ports miso]
set_property PACKAGE_PIN R14 [get_ports led_4]
set_property PACKAGE_PIN P15 [get_ports sda]
set_property PACKAGE_PIN P16 [get_ports scl]
set_property PACKAGE_PIN P14 [get_ports led_5]
set_property PACKAGE_PIN D19 [get_ports push_button_0]
set_property PACKAGE_PIN D20 [get_ports push_button_1]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
